services:
  mongo1:
    container_name: mongo1
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    networks:
      - mongodb-network
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo1:27017',priority:1},{_id:1,host:'mongo2:27017',priority:0.5},{_id:2,host:'mongo3:27017',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  mongo2:
    container_name: mongo2
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27018:27017
    networks:
      - mongodb-network
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    depends_on:
      mongo1:
        condition: service_healthy

  mongo3:
    container_name: mongo3
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27019:27017
    networks:
      - mongodb-network
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    depends_on:
      mongo1:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - 6379:6379
    networks:
      - mongodb-network
    volumes:
      - "redis_data:/data"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
  redis_data:

networks:
  mongodb-network:
    driver: bridge